### ISSUE TITLE
car_crash.wav file is bugged

### ISSUE THREAD

**Issue by race2infinity** [sephiroth7712/PythonMiniProject#3]
This is the error I get when I run the game: 
```
pygame.error: Unable to open file 'car_crash.wav'
```

**Comment by sephiroth7712** [comment]
I'm sorry, this must be a result of shifting to git-lfs for the audio files without having checked if I had exceeded my data limit of the lfs service.
You can expect a solution for this soon.

**Comment by race2infinity** [comment]
Thanks for the alacritous update.

**Comment by sephiroth7712** [comment]
Can you check if the issue still persists?

**Comment by race2infinity** [comment]
The issue has been resolved. Thanks!
